version: 2
project_name: rttlog

before:
  hooks:
    - go mod tidy

builds:
  - id: rttlog
    main: ./cmd/rttlog
    binary: rttlog
    env: [CGO_ENABLED=0]
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
